from typing import Any

from pydantic_ai import Agent, RunContext

from app.src.features.process_user_prompt.ai.core.dependencies import AIFrameworkDependencies


def retrieve_table_metadata_kb(ctx: RunContext[AIFrameworkDependencies]) -> list[dict[str, Any]]:
    """
    Retrieve comprehensive table metadata to populate the agents knowledge base for SQL generation

    This function acts as a tool for AI agents to dynamically access detailed metadata for one or
    more database tables. The metadata includes table definitions, column names, types and
    descriptions, partition keys, and other relevant structural details.

    AI agents should use this function whenever they need to:
    - Validate or map business terms from user questions to actual schema elements.
    - Understand available tables, their columns, and data types.
    - Avoid assumptions about schema and only use what is explicitly available.

    :param ctx: The agent execution context with dependencies and request-specific information.
    :return: A list of dictionaries, each containing metadata about a table.
    """

    # Retrieving objects from the context
    logger = ctx.deps.logger
    logger.info("Called the retrieve_table_metadata_kb tool to retrieve tables metadata")

    kb = ctx.deps.kb_retrieval_repository.retrieve_knowledge_base(
        kb_id=ctx.deps.prompt_request.kb_id
    )
    logger.info("Succesfully finished the call for retrieve_table_metadata_kb tool")

    return kb


def get_dataframe_from_sql_query(
    ctx: RunContext[AIFrameworkDependencies],
    query_string: str
) -> list[dict[str, Any]]:
    """
    Execute a SQL query generated by the agent and return the results as a DataFrame-like structure.

    This function is a tool for AI agents to execute dynamically generated SQL queries typically
    after interpreting a user request and retrieving relevant table metadata. It runs the provided
    SQL query string in the target environment and returns the results as a list of dictionaries,
    where each dictionary represents a row (suitable for DataFrame construction).

    :param ctx: The execution context containing framework dependencies and runtime information.
    :param query_string: The SQL query string generated by the agent to be executed.
    :return: A list of dictionaries suitable for DataFrame-like consumption.
    """

    # Retrieving the logger object from the context
    logger = ctx.deps.logger
    logger.info("Called the get_dataframe_from_sql_query tool to execute the SQL query generated")

    # Running the SQL query using the provided adapter
    df = ctx.deps.query_engine_adapter.run_query(
        query_string=query_string,
        account_credentials=ctx.deps.account_credentials
    )
    logger.info("Succesfully finished the call for get_dataframe_from_sql_query tool")

    return len(df)


def estimate_time_to_build_sql_query(
    ctx: RunContext[AIFrameworkDependencies],
    query_string: str,
    agent: Agent
) -> int:
    """
    Estimate the time required for a typical data analyst with average SQL experience to build
    the given SQL query from scratch.

    This function analyzes the provided SQL query and assesses its expected build time in hours,
    based on factors such as the number of joins, subqueries, aggregations, use of window functions,
    nested queries, and other advanced SQL features.
    The returned QueryBuildEstimate object contains an estimated time (in hours) for a data analyst
    with moderate SQL skills to construct the query, along with reasoning or metrics supporting the
    estimate.

    :param query: The SQL query string to be analyzed.
    :return: A QueryBuildEstimate object with the estimated build time (in hours) and supporting
    details.
    """

    # Retrieving the logger object from the context
    logger = ctx.deps.logger
    logger.info("Called the estimate_time_to_build_sql_query tool to estimate the complexity of the SQL query")

    # Running the SQL query using the provided adapter
    complexity = agent.run_sync(
        user_prompt=query_string,
        deps=ctx.deps
    )
    logger.info("Succesfully finished the call for estimate_complexity_of_sql_query tool")

    return complexity
